name: Build Checker

on: 
  push:
    paths:
        - "src/**"
        - "include/**"
        - "generated_src/**"
        - "generated_include/**"
        - "internal_build_tools/**"
        - "Dependencies/**"

permissions:
  contents: read

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.UEPSEUDO_SSH_KEY }}

    - run: git submodule update --init --recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build_auto.bat Release xinput1_3